### ISSUE TITLE
Split chapters with branches - Question

### ISSUE THREAD

**Issue by NoxFly** [blurrypiano/littleVulkanEngine#13]
Hello,

Why don't you use branches to split the different chapters of your tutorials, so we would have `tuto-01` branch, etc... ?
It would be also easier on your side to maintain and modify the code from all different versions, without having to stock all the versions, cause we'll only want to use one, even if we change. So we could easily do : 
```sh
# active branch : tuto-01
$ make && ./a.out
$ git checkout tuto-02 # change tuto version
$ make && ./a.out
```
So we're on the same solution, but we don't stock all the version in the same directory, and we can run really easily and fastly all the version as we want.

**Comment by simon-cpp** [comment]
> Why don't you use branches to split the different chapters of your tutorials, so we would have `tuto-01` branch, etc... ?

I definitely support this idea, but maybe the restructuring would be too messy

**Comment by blurrypiano** [comment]
ya it might have been a better strategy resulting in a less cluttered directory structure. Once we start getting into the higher tutorial numbers, things might get even more messy, and could make fixing past mistakes much easier.

I'll need to think on it more to decide if the time it takes to switch the project and update all the links in videos to it would be worth it.

**Comment by blurrypiano** [comment]
OK this is mostly completed now and will be how things are done going forward. 

- The new default branch is called **main** which will be the most up to date branch with all tutorial changes
- Branches **tut0-22** and **master** will contain the past tutorials and code. Would've been too much work for not much benefit to create branches for all prior tutorials. Master branch is going to stick around mainly just to not break existing external links into the project
- Future tutorials will use the **tutXX** naming convention, and will be merged as a PR into main when the tutorial becomes public
