### ISSUE TITLE
[FEEDBACK] Vulkan Game Engine Tutorial 02, Capital L and small l : Brendan Galea 

### ISSUE THREAD

**Issue by yeokaiwei** [blurrypiano/littleVulkanEngine#17]
Hi,
I just wanted to give some feedback on Tutorial 02.

I thought I should share it with everyone, just in case they made the same mistake I did.

I made a small mistake with capitalization and the compiler error message will be very confusing.

In 19:15 of your video, you want to create an instance of LvePipeline.

However, if you accidentally type in "LvePipeline" instead of "lvePipeline", you will create a member function instead of creating an instance.

**Severity	Code	Description	Project	File	Line	Suppression State
Error	C2059	syntax error: 'string'	vlkGameEngine	C:\Users\user\source\repos\vlkGameEngine\vlkGameEngine\first_app.h	20**	

![Capture](https://user-images.githubusercontent.com/36597018/145712745-1bb35d8c-132b-491d-951b-a0dfddde5643.PNG)

Thanks.

**Comment by yeokaiwei** [comment]
Once it's set as a member function, it won't be able to change back to an instance.

![Capture](https://user-images.githubusercontent.com/36597018/145713028-e206abbb-4199-40ca-9c6f-fa5f2932b56e.PNG)

**Comment by blurrypiano** [comment]
Thanks for sharing! Please leave future comments like this on the youtube videos itself! Peopline are more likely to see them there (including me)
