### ISSUE TITLE
[FEEDBACK] Tutorial 04 and configInfo{} : Brendan Galea

### ISSUE THREAD

**Issue by yeokaiwei** [blurrypiano/littleVulkanEngine#18]
Encapsulating the instance of `PipelineConfigInfo configInfo{};`  within `PipelineConfigInfo LvePipeline::defaultPipelineConfigInfo(uint32_t width, uint32_t height) ` 
![C](https://user-images.githubusercontent.com/36597018/146177509-c0e7dccd-22fa-4922-9362-d0aca05a9c0f.PNG)

will result in an C2065 error as the compiler can't detect configInfo

![B](https://user-images.githubusercontent.com/36597018/146177504-6299d219-630f-4cbe-b9d6-dff58962ff6f.PNG)

![A](https://user-images.githubusercontent.com/36597018/146177497-9a2ab0c9-d1d2-4a60-83b7-0bd3d3913a0b.PNG)

Is this supposed to happen?

Thank you.

**Comment by blurrypiano** [comment]
hmmm I'm not sure what exactly is going on here, do you not have config info declared above? also a comment on the youtube video for the specific tutorial is preferable. I check the youtube comments more often, and the issues here are really for problems with the codebase, and less so the tutorial content.
