### ISSUE TITLE
[FEEDBACK] Tutorial 07 : Brendan Galea

### ISSUE THREAD

**Issue by yeokaiwei** [blurrypiano/littleVulkanEngine#19]
I felt that reporting this would help other developers who might run into the same issue with undecipherable errors. The code will build and run with no error reported. However, mid-way you will run into the error in the attached image.

If you accidentally leave attributeDescriptions ie 2 instead of 1,
`std::vector<VkVertexInputAttributeDescription> attributeDescriptions(1);`
`std::vector<VkVertexInputAttributeDescription> attributeDescriptions(2);`

you will get the following undecipherable error saying that it "has triggered a breakpoint"
![error](https://user-images.githubusercontent.com/36597018/146678548-9a0465fb-c5e1-4d43-98dc-35244f4ffad9.PNG)

The solution is obviously to set attributeDescriptions(2);

**Comment by blurrypiano** [comment]
thanks for mentioning it, but for something like this I think it would be better suited as a comment on the video! I'm not sure how many viewers would think to look here.
