### ISSUE TITLE
[FEEDBACK] Tutorial 18 Polka Dot Issue : Brendan Galea

### ISSUE THREAD

**Issue by yeokaiwei** [blurrypiano/littleVulkanEngine#24]
Hi Brendan,
I just wanted to post this here to let you know of potential issue with Tutorial 18.

Polka dotted vases using Visual Studio 2019.

I've tried comparing your code and mine but I can't seem to see where the error is.

As always, Youtube does not allow me to upload images, so I felt it was best that you could see it yourself.

![Capture](https://user-images.githubusercontent.com/36597018/147916199-ed3295d3-776a-4e87-ab46-d7cfc61d5724.PNG)
![Capture1](https://user-images.githubusercontent.com/36597018/147916203-6d50484a-a693-4008-9699-7e846873d633.PNG)

**Comment by blurrypiano** [comment]
try the discord
