### ISSUE TITLE
Tutorial 03 not a type name

### ISSUE THREAD

**Issue by Pureya** [blurrypiano/littleVulkanEngine#43]
I'm trying to learn about Vulcan here and While I'm following along with the video in the device header where you paste the constructor pipeline the lveDevice& device, seems to give off that error.
![Screenshot 2023-11-23 005123](https://github.com/blurrypiano/littleVulkanEngine/assets/60141106/f4c868d0-c3e0-46c0-a09b-e9ed0a4cbbfe)

**Comment by simon-cpp** [comment]
ebDevice is either a class or a member of ebPipeline, you can't use the same name.
You have both
`ebDevice&` (meaning: reference to ebDevice type, as a parameter) 
and `ebDevice{ device }`  (meaning: ebDevice = device).
Did you mean to do `device{ device }`?
(This is a special case where parameter/member with the same name is allowed)

**Comment by Pureya** [comment]
It seems I made a mistake in capitalization. Thank you  therpgmaster for your help.

**Comment by simon-cpp** [comment]
> It seems I made a mistake in capitalization. Thank you therpgmaster for your help.

@Pureya  No problem. Happy to help, anytime
